export const REQUEST_CREATE_REQUEST = 'REQUEST_CREATE_REQUEST'
export const REQUEST_CREATE_SUCCESS = 'REQUEST_CREATE_SUCCESS'
export const REQUEST_CREATE_FAIL = 'REQUEST_CREATE_FAIL'

export const REQUEST_GET_ALL_REQUEST = 'REQUEST_GET_ALL_REQUEST'
export const REQUEST_GET_ALL_SUCCESS = 'REQUEST_GET_ALL_SUCCESS'
export const REQUEST_GET_ALL_FAIL = 'REQUEST_GET_ALL_FAIL'

export const REQUEST_CHECK_REQUEST = 'REQUEST_CHECK_REQUEST'
export const REQUEST_CHECK_SUCCESS = 'REQUEST_CHECK_SUCCESS'
export const REQUEST_CHECK_FAIL = 'REQUEST_CHECK_FAIL'
